# Generated by Django 5.0.6 on 2024-05-10 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tygra_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promocao",
            options={"verbose_name_plural": "Promoções"},
        ),
        migrations.AlterField(
            model_name="produto",
            name="promocao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tygra_app.promocao",
            ),
        ),
    ]
